angular.module('chatApplication',['ngRoute','ngMaterial', 'ngMessages','btford.socket-io'])
.config(function($routeProvider,$mdThemingProvider){
  $routeProvider
    .when('/',{
      templateUrl:'views/main.html',
      controller:'mainCtrl'
    })
    .when('/register',{
      templateUrl:'views/register.html',
      controller:'registerCtrl'
    })
    .when('/login',{
      templateUrl:'views/login.html',
      controller:'loginCtrl'
    })
    .when('/chat',{
      templateUrl:'views/chat.html',
      controller:'chatCtrl'
    });
    $mdThemingProvider.theme('default')
        .primaryPalette('teal')
        .accentPalette('deep-orange');
});
